-- Default data for Pinaka Makhana Application
-- This file is automatically executed by Spring Boot on startup

-- Insert default products only if table is empty
INSERT INTO product (
    name, flavor, description, short_description, price, original_price, 
    image_url, rating, review_count, available, stock_quantity, weight, 
    sku, category, is_premium, is_featured, is_new_arrival,
    calories, protein, carbohydrates, fat, fiber,
    meta_title, meta_description, min_order_quantity, 
    shipping_weight, dimensions, created_at, updated_at
) 
SELECT * FROM (
    SELECT 
        'Pinaka Peri Peri Makhana' as name,
        'Peri Peri' as flavor,
        'Experience the perfect blend of spice and crunch with our Peri Peri Makhana. Made from premium quality fox nuts, seasoned with authentic peri peri spices for a tantalizing taste that will leave you craving for more. A healthy snack that doesn''t compromise on flavor!' as description,
        'Spicy and crunchy peri peri flavored makhana - a perfect healthy snack' as short_description,
        299.0 as price,
        349.0 as original_price,
        'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500' as image_url,
        4.5 as rating,
        127 as review_count,
        true as available,
        150 as stock_quantity,
        '100g' as weight,
        'PM-PP-100' as sku,
        'FLAVORED_MAKHANA' as category,
        true as is_premium,
        true as is_featured,
        false as is_new_arrival,
        347.0 as calories,
        9.7 as protein,
        76.9 as carbohydrates,
        0.1 as fat,
        14.5 as fiber,
        'Pinaka Peri Peri Makhana - Spicy Healthy Snack | 100g' as meta_title,
        'Buy premium Peri Peri Makhana online. Healthy, spicy, and crunchy fox nuts perfect for snacking. Free delivery across India.' as meta_description,
        1 as min_order_quantity,
        0.12 as shipping_weight,
        '15x10x5' as dimensions,
        NOW() as created_at,
        NOW() as updated_at
    
    UNION ALL
    
    SELECT 
        'Pinaka Cheese Makhana',
        'Cheese',
        'Indulge in the rich and creamy taste of our Cheese Makhana. Premium fox nuts coated with authentic cheese powder, creating a perfect balance of health and taste. Ideal for cheese lovers who want to snack guilt-free!',
        'Creamy cheese flavored makhana for the ultimate snacking experience',
        279.0,
        329.0,
        'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500',
        4.3,
        89,
        true,
        120,
        '100g',
        'PM-CH-100',
        'FLAVORED_MAKHANA',
        true,
        false,
        true,
        352.0,
        10.2,
        75.8,
        0.3,
        14.2,
        'Pinaka Cheese Makhana - Creamy Healthy Snack | 100g',
        'Delicious cheese flavored makhana made from premium fox nuts. Perfect healthy snack for kids and adults. Order online now!',
        1,
        0.12,
        '15x10x5',
        NOW(),
        NOW()
    
    UNION ALL
    
    SELECT 
        'Pinaka Puddina Makhana',
        'Mint (Puddina)',
        'Refresh your taste buds with our Puddina Makhana. Premium fox nuts infused with fresh mint flavor, offering a cool and refreshing snacking experience. Perfect for those who love the invigorating taste of mint combined with healthy nutrition!',
        'Refreshing mint flavored makhana for a cool and healthy snack',
        289.0,
        339.0,
        'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500',
        4.4,
        76,
        true,
        100,
        '100g',
        'PM-PD-100',
        'FLAVORED_MAKHANA',
        false,
        true,
        true,
        345.0,
        9.5,
        77.2,
        0.1,
        14.8,
        'Pinaka Puddina Makhana - Mint Flavored Healthy Snack | 100g',
        'Fresh mint flavored makhana made from premium fox nuts. Refreshing and healthy snack perfect for any time. Buy online!',
        1,
        0.12,
        '15x10x5',
        NOW(),
        NOW()
    
    UNION ALL
    
    SELECT 
        'Pinaka Classic Salted Makhana',
        'Classic Salted',
        'Our signature Classic Salted Makhana represents the pure essence of premium fox nuts. Lightly salted to perfection, these crunchy delights offer the authentic taste of makhana while providing excellent nutrition. The perfect introduction to the world of healthy snacking!',
        'Premium classic salted makhana - pure, healthy, and delicious',
        249.0,
        299.0,
        'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500',
        4.6,
        203,
        true,
        200,
        '100g',
        'PM-CS-100',
        'ROASTED_MAKHANA',
        false,
        true,
        false,
        347.0,
        9.7,
        76.9,
        0.1,
        14.5,
        'Pinaka Classic Salted Makhana - Premium Fox Nuts | 100g',
        'Premium quality classic salted makhana. Healthy, crunchy, and delicious fox nuts perfect for guilt-free snacking. Order now!',
        1,
        0.12,
        '15x10x5',
        NOW(),
        NOW()
) AS tmp
WHERE NOT EXISTS (SELECT 1 FROM product LIMIT 1);
